force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlightStatusBatch.cls
global class FlightStatusBatch
implements Database.Batchable<SObject> {

    global Database.QueryLocator start(
        Database.BatchableContext bc
    ) {

        return Database.getQueryLocator(
            [
                SELECT Id,
                       Status__c,
                       Departure_DateTime__c
                FROM Flight__c
                WHERE Departure_DateTime__c < :System.now()
            ]
        );
    }

    global void execute(
        Database.BatchableContext bc,
        List<Flight__c> scope
    ) {

        for(Flight__c flight : scope){

            flight.Status__c = 'Completed';
        }

        update scope;
    }

    global void finish(
        Database.BatchableContext bc
    ) {

        System.debug(
            'Flight Status Batch Completed'
        );
    }
}